import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id),root='/home/dev/project/3d/gpt6_astra_pro_mcp_blender_rgirl_top_half';
const titles={front:'Front portrait',threequarter:'Three-quarter portrait',side:'Profile study',back:'Rear groom study',detail:'Face detail',orbit:'Interactive 3D bust'};
let data=null,currentView='front',signature='',renderer,scene,camera,controls,model,loadedModel='',frame=0,turntable=false,wire=false;
const errors=[];window.__studio={errors,modelLoaded:false,views:[],revision:0};
const safe=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function error(message){errors.push(message);$('viewer-error').textContent=message;$('viewer-error').hidden=false;}
function fileUrl(path){return './'+path+(data?'?v='+encodeURIComponent(data.version):'');}
function updateView(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));$('view-title').textContent=titles[currentView];$('engine-label').textContent=currentView==='orbit'?'LIVE WEBGL':'EEVEE RENDER';const is3d=currentView==='orbit';$('viewer').hidden=!is3d;$('main-image').hidden=is3d;$('orbit-tools').hidden=!is3d;$('viewer-error').hidden=true;if(is3d){$('empty').hidden=!!model;init3D();loadModel();$('active-path').textContent=data?.files?.glb?.absolute||root+'/build/gpt6_astra_pro_mcp_blender_rgirl_top_half.glb';$('file-description').textContent='Web model · drag to orbit · scroll or pinch to zoom';startFrame();}else{cancelAnimationFrame(frame);frame=0;const view=data?.views?.find(v=>v.id===currentView);$('empty').hidden=!!view;$('main-image').hidden=!view;if(view){const url=fileUrl(view.path);if($('main-image').getAttribute('src')!==url)$('main-image').src=url;$('main-image').alt=titles[currentView]+' — original Blender EEVEE render';$('active-path').textContent=view.absolute;$('file-description').textContent='Actual Blender EEVEE output · '+(view.resolution||'');}}}
function init3D(){if(renderer)return;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,innerWidth<760?1.5:1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('viewer').appendChild(renderer.domElement);scene=new THREE.Scene();scene.background=new THREE.Color('#302c30');camera=new THREE.PerspectiveCamera(31,1,.05,60);camera.position.set(0,2.35,8.3);controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.94,0);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=2.1;controls.maxDistance=12;controls.maxPolarAngle=Math.PI*.90;controls.autoRotateSpeed=.65;scene.add(new THREE.HemisphereLight(0xf7f1e9,0x6c6873,1.1));function lamp(color,intensity,p){const l=new THREE.DirectionalLight(color,intensity);l.position.set(...p);scene.add(l);return l;}const key=lamp(0xffe7d5,2.6,[-3.5,5.4,4.5]);key.castShadow=true;key.shadow.mapSize.set(innerWidth<760?512:1024,innerWidth<760?512:1024);key.shadow.camera.left=-3;key.shadow.camera.right=3;key.shadow.camera.top=5;key.shadow.camera.bottom=-2;key.shadow.normalBias=.015;key.shadow.bias=-.00015;lamp(0xcbdfff,.85,[3,3,3]);lamp(0xffdcc0,2,[2,4.8,-2]);const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x302c30,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.035;floor.receiveShadow=true;scene.add(floor);new ResizeObserver(resize).observe($('stage'));resize();}catch(e){error('WebGL could not start. The Blender images and files remain available. '+e.message);}}
function resize(){if(!renderer)return;const r=$('stage').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}
function startFrame(){if(frame||!renderer||currentView!=='orbit')return;const render=()=>{frame=0;if(currentView!=='orbit'||document.hidden)return;controls.autoRotate=turntable;controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(render);};frame=requestAnimationFrame(render);}
function dispose(object){object.traverse(o=>{o.geometry?.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m?.dispose());});}
function loadModel(){const f=data?.files?.glb;if(!f||!renderer)return;const key=f.path+'@'+data.version;if(key===loadedModel)return;loadedModel=key;new GLTFLoader().load(fileUrl(f.path),gltf=>{if(model){scene.remove(model);dispose(model);}model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.wireframe=wire;m.side=THREE.DoubleSide;});}});scene.add(model);$('empty').hidden=true;window.__studio.modelLoaded=true;window.__studio.modelBounds=new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).toArray();startFrame();},undefined,e=>{loadedModel='';error('The 3D file could not load. Try an image view while it is being published. '+e.message);});}
function refreshUI(next){data=next;document.querySelectorAll('[data-view]').forEach(b=>{b.disabled=b.dataset.view==='orbit'?!data.files?.glb:!data.views?.some(v=>v.id===b.dataset.view);});window.__studio.revision=data.revision||0;window.__studio.views=(data.views||[]).map(v=>v.id);$('revision-chip').textContent='REV '+String(data.revision||1).padStart(2,'0');$('stage-index').textContent='REVISION '+String(data.revision||1).padStart(2,'0')+' / ORIGINAL GEOMETRY';$('score').textContent=data.score??'—';$('score-fill').style.width=(data.score||0)+'%';$('review-note').textContent=data.note||'Awaiting visual review.';$('rounds').textContent=data.history?.length||0;$('updated').textContent='UPDATED '+(data.updated||'').replace('T',' ').slice(0,16)+' UTC';$('model-stats').textContent=data.modelStats||'';for(const key of ['blend','glb','zip']){const a=$('download-'+key),f=data.files?.[key];if(f){a.href=fileUrl(f.path);a.classList.remove('disabled');a.setAttribute('aria-disabled','false');a.setAttribute('download','');}}$('download-paths').innerHTML=Object.entries(data.files||{}).map(([k,f])=>'<p class="label">'+safe(k.toUpperCase())+'</p><code class="small-path">'+safe(f.absolute)+'</code>').join('');$('journal').innerHTML=[...(data.history||[])].reverse().map(h=>'<div class="journal-item"><span class="round">'+String(h.iteration).padStart(2,'0')+'</span><div><h3>'+safe(h.title)+'</h3><p>'+safe(h.note)+'</p></div><span class="journal-score">'+safe(h.score)+'</span></div>').join('')||'<p>The first render is in progress.</p>';$('gallery').innerHTML=[...(data.views||[])].sort((a,b)=>(b.order||0)-(a.order||0)).map(v=>'<article class="gallery-card"><button data-gallery="'+safe(v.id)+'" aria-label="Show '+safe(titles[v.id])+'"><img loading="lazy" src="'+fileUrl(v.path)+'" alt="'+safe(titles[v.id])+' Blender render"></button><div><h3>'+safe(titles[v.id])+'</h3><code>'+safe(v.absolute)+'</code></div></article>').join('')||'<div class="gallery-placeholder">Views will appear after each completed render.</div>';document.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>{currentView=b.dataset.gallery;updateView();$('stage').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});}));updateView();}
async function poll(){try{const res=await fetch('./status.json?time='+Date.now(),{cache:'no-store'});if(!res.ok)return;const next=await res.json();const sig=JSON.stringify(next);if(sig!==signature){signature=sig;refreshUI(next);}$('live-label').textContent='Latest published build';}catch(e){$('live-label').textContent='Saved studio preview';}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{currentView=b.dataset.view;updateView();}));$('reset-view').addEventListener('click',()=>{camera.position.set(0,2.35,8.3);controls.target.set(0,1.94,0);controls.update();});$('rotate').addEventListener('click',()=>{turntable=!turntable;$('rotate').setAttribute('aria-pressed',String(turntable));});$('wireframe').addEventListener('click',()=>{wire=!wire;$('wireframe').setAttribute('aria-pressed',String(wire));model?.traverse(o=>{if(o.material){const a=Array.isArray(o.material)?o.material:[o.material];a.forEach(m=>m.wireframe=wire);}});});$('reference-open').addEventListener('click',()=>$('reference-dialog').showModal());$('reference-close').addEventListener('click',()=>$('reference-dialog').close());$('reference-dialog').addEventListener('click',e=>{if(e.target===$('reference-dialog'))e.target.close();});document.addEventListener('visibilitychange',()=>{if(!document.hidden){poll();startFrame();}});window.addEventListener('error',e=>errors.push(e.message));poll();setInterval(poll,5000);
